### ISSUE TITLE
Remaining Features & Design Bits

### ISSUE THREAD

**Issue by dstrogiy** [VCUarts/GDES-2015#2]
## Features
- [x] MFA Alumni
- [x] Student work on the BFA overview page
- [x] Work archive thumbnails displayed on MFA/BFA - add an option to make it white & blue with text showing right away 

## Design
- [x] the main menu layout looks different from Alex's demo
- [x] Add link to MFA alumni in the main menu
- [x] In Alex's version you can still see the main menu in the background as a texture which looks kinda cool

## Aand
- [ ] Mobile version
- [x] Faculty headshots

**Comment by dstrogiy** [comment]
Are we gonna try to emulate that loading screen with the rotating gif?

**Comment by streeetlamp** [comment]
I wasn't planning on it, any objections?

**Comment by dstrogiy** [comment]
Nope

**Comment by dstrogiy** [comment]
Also
- [ ] Faculty headshots

**Comment by dstrogiy** [comment]
- [ ] Work archive thumbnails displayed on MFA/BFA - add an option to make it white & blue with text showing right away
