### ISSUE TITLE
More Remaining Features and Design Bits

### ISSUE THREAD

**Issue by PeytonSorah** [VCUarts/GDES-2015#3]
- [x]  All text colors need to be #404040
- [x]  the nav items are on every page bg on the original site, should we emulate that?
- [x] Missing MFA Alumni main nav item 

MFA single pages: 
 - [x] Need borders around images
- [x]  “x” goes to work page and not back to MFA
- [x]  footer should be hidden (cody note: I'm gonna leave it visible anyway)
- [x]  much more padding at bottom (looks like they have about 300px? of white)
- [x] name of work should be italicized (cody note: ignoring for now)

BFA
- [x] course list needs to be styled
- [x] course list page is missing menu
- [x] course catalog link is missing

MFA
- [x] List of students on landing page is missing a border/background

Diversity
- [x] Missing MFA Alumni main nav item more padding at bottom

Faculty
- [x] General Styling

**Comment by dstrogiy** [comment]
^ I think the BFA course catalog content is already present on the courses page, so I think we don't have to add the link to the vcu bulletin site. It's also not shown in the nav on this page - http://www.alexalexmartin.com/GDES/bfa/

**Comment by PeytonSorah** [comment]
@dstrogiy I totally agree that it isn't a necessary add-but for some reason it does show up in the nav on their BFA section, but only if you're on the "courses" page first. Really strange.
